### ISSUE TITLE
Diagram confusion use vs aggregation in scene

### ISSUE THREAD

**Issue by djmisterjon** [dodocloud/games-course#1]
hi friend, your course of your engine are awesome ! thank for share that's!
I just have one thing that's confuse me for now in your diagram!
In your diagram you say `Scene` class use `GameObject`
![image](https://user-images.githubusercontent.com/24865815/120930037-8fdff280-c6b9-11eb-9de0-4e0a7f2eb9ef.png)

But after look deeper in your engine, it seem aggregate your class `GameObject` as `Container` ?
Is your article or diagram where is outdate ? Or i am wrong ?
Am not pro in UML, but i using this reference.
http://usna86-techbits.blogspot.com/2012/11/uml-class-diagram-relationships.html
![image](https://user-images.githubusercontent.com/24865815/120930307-b5b9c700-c6ba-11eb-9f83-d8d96bfe3402.png)
So i should read `has` or `own`?

**Comment by dodocloud** [comment]
Hello there,

sorry for the delayed response, I totally forgot 😁...

the diagrams are UML-based, yes, but the archetypes were redesigned for the benefit of more geekery design.
When I was reading your message while looking at my diagram, I got confused as well, to be honest 😁.
Yes, the diagram is wrong, and thanks for pointing this out! The `<<uses>>` archetype meant that `Scene` communicated with other objects through this interface. But now, it uses directly the type of `Container`.

The arrow can be removed completely and replaced with a `1-1` aggregation that would indicate that the `Scene` has a pointer to the `stage` object

I'll come back to this issue by the end of this week and fix it.
Thanks again

**Comment by djmisterjon** [comment]
> Hello there,
> 
> sorry for the delayed response, I totally forgot 😁...
> 
> the diagrams are UML-based, yes, but the archetypes were redesigned for the benefit of more geekery design.
> When I was reading your message while looking at my diagram, I got confused as well, to be honest 😁.
> Yes, the diagram is wrong, and thanks for pointing this out! The `<<uses>>` archetype meant that `Scene` communicated with other objects through this interface. But now, it uses directly the type of `Container`.
> 
> The arrow can be removed completely and replaced with a `1-1` aggregation that would indicate that the `Scene` has a pointer to the `stage` object
> 
> I'll come back to this issue by the end of this week and fix it.
> Thanks again

hey thank you for the confirmation, because I confess that when looking at the code and the diagram, I got some confusion, even when you are sure of yourself, it sows doubt and makes learning difficult.
So if you have time to make a more verbose diagram, this will awesome ! It help a lot for visual people like me !

ps: I would like to thank you for having shared all this documentation (hard work behind), it is fascinating! 
Currently I am interested in a hybrid architecture of ECS with TS for making a Software, but it is very difficult to find documentation on good approach of ECS oriented sofware, a lot of wall ! ,but currently reading your guide for games helps me a lot and inspires me on approach that I will never even imagine ! 
So big thanks and no worry for late response , i understand :)

**Comment by dodocloud** [comment]
Hi,

at long last, I fixed this. Sorry for the delay (you know, vacations and other projects...), and many thanks for your patience and appreciation in your last comment.

The diagram should represent the current state - GameObject interface is only used internally to force objects derived from PIXI to implement ECS functions. Components and the Scene work directly with the derived ECS Container, as it can access both the PIXI and ECS functions.

**Comment by djmisterjon** [comment]
> Hi,
> 
> at long last, I fixed this. Sorry for the delay (you know, vacations and other projects...), and many thanks for your patience and appreciation in your last comment.
> 
> The diagram should represent the current state - GameObject interface is only used internally to force objects derived from PIXI to implement ECS functions. Components and the Scene work directly with the derived ECS Container, as it can access both the PIXI and ECS functions.

Ho , thanks for the fix and your time ! i shared littlebit your tutoproject on discords and slack people love it!
if you want joint social club to share your work!
pixijs discords
https://discord.gg/C6r7PFKrwt
and pixijs slack
https://pixijs.slack.com/join/shared_invite/zt-dcem1map-uVuVGC7pZ0trF8SrcA2p9g
